### ISSUE TITLE
Undeclared variable when using cURL

### ISSUE THREAD

**Issue by fade2gray** [oneall/social-login-phpbb#10]
Undeclared variable `$header_found` affects...

OneAll v3.6 for phpBB v3.0.x
line# 1545 **functions_oa_social_login.php**
`while ( ! $header_found && (list (, $header) = each ($result->http_headers)))`

OneAll v2.1 for phpBB v3.1.x
line# 1105 **sociallogin_acp_module.php**
`while (! $header_found && (list (, $header) = each ($result->http_headers)))`

**Comment by SchlesserClaude** [comment]
Thank you very much for the bug report! I have now added a bugfix.
