### ISSUE TITLE
Redirect error from oauth

### ISSUE THREAD

**Issue by JohnnySSH** [oneall/social-login-phpbb#11]
General Error
SQL ERROR [ postgres ]

ERROR: syntax error at or near "LIMIT" LINE 1: ...ntity_token = 'cbed1dc9-ed8a-4688-9a51-0d6dbd519c2b' LIMIT 1 ^ []

An SQL error occurred while fetching this page. Please contact the Board Administrator if this problem persists.

**Comment by SchlesserClaude** [comment]
Should be fixed now: https://github.com/oneall/social-login-phpbb/commit/86407c5097a4672c130ce3c1f9b8b5a1735064f4
