### ISSUE TITLE
Incorrect url profile

### ISSUE THREAD

**Issue by kMakoto** [oneall/social-login-phpbb#13]
registrate using youtube, in profile , website generate url "https://gdata.youtube.com/feeds/api/users/2TWYuM9wAvIOAEHEVwEh-g"
is correct?

using facebook, in profile, website generate url "https://www.facebook.com/app_scoped_user_id/399518646869855/"
is not better "https://www.facebook.com/usermane" ???

**Comment by SchlesserClaude** [comment]
For privacy reasons Facebook unfortunately no longer provides the username and only a scoped userid (each app has a different id for the same user). I'll have a look at Youtube ;)
