### ISSUE TITLE
Out of range value for column 'date_added' at row 1 [1264]

### ISSUE THREAD

**Issue by SiB57** [oneall/social-login-phpbb#14]
I have a brand new phpbb (my first phpbb that I've setup, but I'm the "tech guy" for my club.)  One of the primary use cases was to allow facebook logins so users wouldn't  have to have two separate logins to keep track of.

Installed phpbb and the social plugin and that's pretty much it. Setup social plugin and the facebook login appears to work and a user is added to the system but login doesn't work.  I get this error:

General Error
SQL ERROR [ mysql4 ]

Out of range value for column 'date_added' at row 1 [1264]

An SQL error occurred while fetching this page. Please contact the Board Administrator if this problem persists.

I think I'm using the very latest phpbb (3.1.2) and I download the github version of the social plugin.  Did I miss an obvious step?

**Comment by SchlesserClaude** [comment]
Hello,

Could you please open your database, locate the table “oasl_user” (the table 
name might have a prefix) and change the column date_added to “INT 15”.

We will also release a new version with a bug fix tomorrow.

Regards,

Claude Schlesser
___________________
ONEALL LLC (SARL)
http://www.oneall.com/
Social Media Integration Made Easy

CEO & Founder
cschlesser@oneall.com
http://www.linkedin.com/in/claudeschlesser
