### ISSUE TITLE
FRENCH or others languages - To use of accented chars

### ISSUE THREAD

**Issue by Galixte** [oneall/social-login-phpbb#16]
Hi,

in ACP for the next three input fields :

```
	'OA_SOCIAL_LOGIN_REGISTRATION_PAGE_CAPTION_DESC' => 'This title is displayed above the Social Login icons on the registration page.',
```
```
	'OA_SOCIAL_LOGIN_LOGIN_PAGE_CAPTION_DESC' => 'This title is displayed above the Social Login icons on the login page.',
```
```
	'OA_SOCIAL_LOGIN_INDEX_PAGE_CAPTION_DESC' => 'This title is displayed above the Social Login icons on the main page.',
```

On my board, with FRENCH language i can't to use any accented chars.

If i use this FRENCH text :
```
Connectez-vous avec votre compte de réseau social
```

After update the settings, the field will be changed by this :

```
Connectez-vous avec votre compte de r??seau social
```

**Comment by SchlesserClaude** [comment]
I think that you may have to add the encoding in your language files.

Try to add this:

$lang['ENCODING'] = 'iso-8859-1';
or this:

$lang['ENCODING'] = 'UTF-8';

To your translated files.

**Comment by Galixte** [comment]
Bonjour,

ce texte accentué :

```
Connectez-vous avec votre compte de réseau social
```

Il ne fait pas partie de mes fichiers de traductions. C'est le texte que je souhaite voir affiché sur les trois pages correspondant aux champs cités précédemment.

**Comment by SchlesserClaude** [comment]
Bonjour,

Merci pour les détails. 

Le problème est maintenant corrigé!
Voici les changements: https://github.com/oneall/social-login-phpbb/commit/c56626cc6e490a5467213a163c6c29cf6310af85?w=1

**Comment by Galixte** [comment]
Je vous remercie !
