### ISSUE TITLE
New registration with Social Network account & "New member post limit" option

### ISSUE THREAD

**Issue by Galixte** [oneall/social-login-phpbb#17]
Hi,
i try all functionalities of your extension and they are pretty cool, thanks for job !

I found an error with phpBB 3.1.2.

If i activated the next option on my board :

```
New member post limit:
New members are within the Newly Registered Users group until they reach this number of posts. You can use this group to keep them from using the PM system or to review their posts. A value of 0 disables this feature.
```
This option allows, by example, to limit the news users to post some messages before approbation.

Your extension doesn't respect the fact that the news users registered have to be placed in the "Newly Registered Users" group.

Could you make in sort to take in consideration the fact to activate this option ?

**Comment by SchlesserClaude** [comment]
Hello,

Thank  you for the  bug report.

That problem should now be fixed:
https://github.com/oneall/social-login-phpbb/commit/0df3a3b1229cf92d11bf7922b67eb92cf7841255

(Line 1934-1939)

**Comment by Galixte** [comment]
Thanks for fix ;=)
