### ISSUE TITLE
Require Twitch account link

### ISSUE THREAD

**Issue by SubliminallyFamous** [oneall/social-login-phpbb#22]
Hello,
 I'm sorry but I cannot find a support page for the 3.1 extension which is why I have posted this here.

 Is there a way to require a member to register through clicking the "sign up with twitch" button, so that every member has a linked twitch account?

 It's important for me for moderation reasons between Twitch chat and the forum.

 Many thanks

**Comment by SchlesserClaude** [comment]
Hello,

you could remove the username/password login form so that your users have no other choice but to use Twitch ;)

Regards,

**Comment by SubliminallyFamous** [comment]
Hi there, thanks for your response.
I had thought of doing this, but there are so many places that redirect to the registration/login page I still haven't thought of an effective way to do this.
At the moment I'm considering creating a custom registration page with the "connect with twitch" button for people to click, and then redirect all from the register and login pages to that.

If you have any other ideas, or if there's a simpler way please share!

Thanks
