### ISSUE TITLE
Column 'user_token' cannot be null [1048]

### ISSUE THREAD

**Issue by Behraka** [oneall/social-login-phpbb#25]
Hey. 

After installing the plugin for my PHPBB forums, after a few weeks I receive the following error.

SQL ERROR [ mysqli ]

Column 'user_token' cannot be null [1048]

An SQL error occurred while fetching this page. Please contact the Board Administrator if this problem persists.

I set up the plugin so users can login/register using their Steam account but they have reported to have encountered the error above. Needless to say, the plugin was working perfectly and no changes were applied to the database, the PHP files or anything related to either of them.

How can I sort out this issue? Thanks in advance and great work on the plugin!

**Comment by SchlesserClaude** [comment]
Hello, could you please posts to a link to a page where I can see the error?

**Comment by Behraka** [comment]
Hi.

http://fwkzt.com/index.php

The error occurs when a user clicks on the Steam login, enters their credentials and waits for a redirect but encounters the error.

Oddly enough, it seems to work now after I disabled and enabled the plugin.

**Comment by frdpnl** [comment]
Hi,
This error can occur when there is some API communication problems between OneAll and the provider (such as Steam). We've added some error handling for this, but the root cause is the communication error, which must be fixed.
