### ISSUE TITLE
3.1 disabled extension does not remove the ext page

### ISSUE THREAD

**Issue by SiteSplat** [oneall/social-login-phpbb#26]
Looks like there is a problem when you disable the ext. All the entries should not be available under the extension tab. You are left with a broken page until you delete the data.

Dave

**Comment by frdpnl** [comment]
Hi, 
Thanks for reporting the error.
Regards.

**Comment by frdpnl** [comment]
Hi,
We've now fixed the error, and will be posting an updated version soon.
Thanks again for your report.

**Comment by SchlesserClaude** [comment]
Should be fixed!
