### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by MuNDuNGu** [oneall/social-login-phpbb#27]
Error General
Illegal use of $_POST. You must use the request class or request_var() to access input data. Found in /home/content/p3pnexwpnas10_data02/48/2692648/html/foro/includes/functions_oa_social_login.php on line 278. This error message was generated by deactivated_super_global.

Error in http://podemosesteponacirculo.info/foro/

Can you help me? Thank you

**Comment by RMcGirr83** [comment]
Why are you using a 3.0 mod in a 3.1 phpBB forum?  You should be using the 3.1 version not the 3.0 version.

**Comment by neuropass** [comment]
I guess its easy to get confused somewhat. I ran into the same issue as well. Then realized I used the wrong package. Also you might want to consider to use a premium theme like this one: http://themeforest.net/item/flatboots-phpbb-31-and-30-/8536771?ref=ThemeSplat 
Good luck!

**Comment by deeqfinch** [comment]
helllo. why was this issue closed . im still having this.
and im using the 3.1 extnetion on a 3.1.x forum.
please help

**Comment by Galixte** [comment]
Hi,

did you updated your from forum a phpBB 3.0.x previously ? If yes, did you use the equivalent MOD of this extension on your forum ?

What is the URL address of your forum ?
What is the error message ?

More there are informations, more you will have a chance to get a support.

**Comment by deeqfinch** [comment]
my forum is very new . its a fresh 3.1 installed. 
and i carefully fresh installed the 2.4.7 , oneall extentionsion

http://myshelf.in/  = the forum
(have only configured facebook)
the error msg =
General Error
Illegal use of $_POST. You must use the request class or request_var() to access input data. Found in /home/mayank115anu/public_html/includes/functions_oa_social_login.php on line 122. This error message was generated by deactivated_super_global.


thanks

**Comment by frdpnl** [comment]
Hi,
The file raising the error is part of the MOD for PhpBB 3.0.
So, you may have leftover files from the MOD. Delete them before installing the 3.1 Extension.

Hope this helps.

**Comment by deeqfinch** [comment]
@frdpnl 
thx for replying.

no chance bro.
i just deleted everything in the EXT folder of forum and installed 
the fresh download from github 2.4.6 one for >= 3.1

**Comment by frdpnl** [comment]
Ah, but the MOD (for 3.0) installation copies files in other directories.
Such as: /home/mayank115anu/public_html/includes/functions_oa_social_login.php.
Remove the MOD directories, as in http://docs.oneall.com/plugins/guide/social-login-phpbb/3.0/, you can also edit the template fles again.
And clear your PhpBB cache.

**Comment by deeqfinch** [comment]
@frdpnl 
thx a lot working like a charm.
