### ISSUE TITLE
Provider Oauth Externe

### ISSUE THREAD

**Issue by Romain17** [oneall/social-login-phpbb#39]
Bonjour,

je viens d'utiliser votre plugin afin d'ajouter une authentification via les réseaux sociaux sur mon forum. Votre extension marche très bien et est très simple d'utilisation!
Je voudrais savoir si votre extension permet d'ajouter son propre provider SSO basé sur le protocole OAuth ? En effet, ayant développer mon propre système afin que les utilisateurs de mes logiciels est un seul compte à gérer, je voudrais qu'il puisse en faire de même avec le forum.

Merci d'avance,
Cordialement, Romain

**Comment by SchlesserClaude** [comment]
Bonjour Romain,

le plugin permettrait de faire du SSO qui serait par contre basé sur le Social Login. Donc si l'utilisateur se connect avec Facebook sur le premièr forum, il serait automatiquement connect avec le même comte Facebook s'il visite le deuxième forum.

Le SSO est décrit dans notre document, nous ne l'avons par contre pas encore ajouté au plugin. http://docs.oneall.com/services/implementation-guide/single-sign-on/

**Comment by Romain17** [comment]
Merci pour votre réponse!
