### ISSUE TITLE
Unable to retrieve Facebook user avatar

### ISSUE THREAD

**Issue by fade2gray** [oneall/social-login-phpbb#5]
Unable to retrieve Facebook user avatar.

functions_oa_social_login.php - @getimagesize($file_tmp_name) returns bool:false

Any way I can debug this?

(no problems retrieving avatar in SMF)

**Comment by SchlesserClaude** [comment]
Sorry, I can't reproduce the error. Could you send us a support ticket with a link to your forum? We will give it a try. http://www.oneall.com/company/contact-us/
