### ISSUE TITLE
Can't edit text

### ISSUE THREAD

**Issue by CarstenKS** [oneall/social-login-phpbb#53]
Hi,
Thanks for the lovely plugin - I can´t however not edit this text, see attached image.
Other texts edits fine.
![2017-05-20 18_46_59-oneall social login](https://cloud.githubusercontent.com/assets/28828455/26277711/bece6748-3d8d-11e7-81c5-4ee9b76f7bae.png)

**Comment by Galixte** [comment]
Hi @CarstenKS @SchlesserClaude,

strange, i don't have this problem (with english & french).

Which language do you use ? Did you try to purge the forum cache, your browser cache, close your browser and relaunch it to try again ?

**Comment by CarstenKS** [comment]
Hi @Galixte 
Thanks for your reply.
My language setting are Danish. The forum is located at citroenforum.dk if that should be relevant.

I have purged the cache, reloading the browser, etc. I have tried with both Firefox and Chrome. But no luck.

**Comment by Galixte** [comment]
Try to upload the files from this extension (dot not replace, delete them before upload) and purge the board cache again.

**Comment by CarstenKS** [comment]
@Galixte 
I just tried to delete data, purge cache, delete files via FTP, re-upload - The same thing happen. Really weird.

**Comment by SchlesserClaude** [comment]
@CarstenKS 
if I understand correctly, the field is write-protected? 
Or can you modify it's value and it's not saved?

**Comment by CarstenKS** [comment]
I can modify it's value, but it's not saved, for some reason unknown to me. Even though phpBB says "Succesful changes", or whatever it may translate to - I see the green bar on the top, that settings are saved.

**Comment by SchlesserClaude** [comment]
This error has now been fixed:
https://github.com/oneall/social-login-phpbb/commit/043f597271f0a2cb05b02acaea5a7e91a6824e60?w=1
