### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by odddellarobbia** [oneall/social-login-phpbb#58]
I've seen you added Discord Login for your wordpress login, any plan to add it to your phpbb extention?

**Comment by zaradamien** [comment]
Hi, it will be added very soon with Weibo too.

**Comment by SchlesserClaude** [comment]
Add in the new version:
https://github.com/oneall/social-login-phpbb/commit/4470fbeebd5ad4ec95fce367cab928a52de628fb
