### ISSUE TITLE
SocialLogin isn't visible on the index page - $this->php_ext

### ISSUE THREAD

**Issue by b-vetter** [oneall/social-login-phpbb#59]
https://github.com/oneall/social-login-phpbb/blob/dce1dc76b8311d9271cbabf3b8208b69e42b44a3/%5B%20%3E%3D%203.1.%20%5D%20EXTENSION/oneall/sociallogin/event/listener.php#L179

$this->php_ext doesn't work on this position.
I'm not sure whether it is filled at all. I haven't checked.

I've changed this line back to:
` if (! empty ($this->user->page['page_name']) && $this->user->page['page_name'] == 'index.php')`

Without that change, the login isn't visible on the index page. 😬 
Please check that!

Thank you! 👍

**Comment by SchlesserClaude** [comment]
Hello,

When we submitted the plugin to the official phpBB repository, the staff asked us to replace .php by $this->php_ext!

in our test environment we could not replace the issue.

It might be better to replace it with a test that does not rely on the variable.

`if (! empty ($this->user->page['page_name']) && strpos($this->user->page['page_name'], 'index') !== false)`
