### ISSUE TITLE
Activating the extantion error

### ISSUE THREAD

**Issue by ghost** [oneall/social-login-phpbb#64]
Hi,
I had to reinstall phpBB from scratch. Wiped the database and all. Went to setup the plug-in and I keep getting the error:
Something went wrong during the request and an exception was thrown. The changes made before the error occurred were reversed to the best of our abilities, but you should check the board for errors.
A module already exists: OA_SOCIAL_LOGIN_ACP
 Any help with this problem is welcome. Thank you.

**Comment by SchlesserClaude** [comment]
Hello,

you can run the following query to remove the corresponding entry from your database:

> DELETE FROM `phpbb_modules` WHERE `module_langname` LIKE 'OA_SOCIAL_LOGIN%'

Then you should be able to re-install the module.

**Comment by ghost** [comment]
That got it, THANK YOU

**Comment by SchlesserClaude** [comment]
Thank you for the update and a great 2018 ;)
