### ISSUE TITLE
Issue while activating plugin

### ISSUE THREAD

**Issue by ashishpatel1992** [oneall/social-login-phpbb#66]
Recently upgraded plugin from 2.4.0 to 4.5.2 and got error upon activating plugin
`A module already exists: OA_SOCIAL_LOGIN_ACP`

**Comment by ashishpatel1992** [comment]
Here is the detail error:
`Fatal error: Uncaught exception 'phpbb\module\exception\module_exception' with message 'CANNOT_REMOVE_MODULE' in /home/mysite/public_html/forum/phpbb/module/module_manager.php:448 Stack trace: #0 /home/mysite/public_html/forum/phpbb/db/migration/tool/module.php(371): phpbb\module\module_manager->delete_module(548, 'acp') #1 [internal function]: phpbb\db\migration\tool\module->remove('acp', 'ACP_CAT_DOT_MOD...', 'OA_SOCIAL_LOGIN...') #2 /home/mysite/public_html/forum/phpbb/db/migration/tool/module.php(405): call_user_func_array(Array, Array) #3 [internal function]: phpbb\db\migration\tool\module->reverse('add', 'acp', 'ACP_CAT_DOT_MOD...', 'OA_SOCIAL_LOGIN...') #4 /home/mysite/public_html/forum/phpbb/db/migrator.php(711): call_user_func_array(Array, Array) #5 /home/mysite/public_html/forum/phpbb/db/migrator.php(680): phpbb\db\migrator->run_step(Array, false, true) #6 /home/mysite/public_html/forum/phpbb/db/migrator.php(436): phpbb\db\migrator->process_data_step(Array, Array) #7 /home/mysite/public_html/forum/ in /home/mysite/public_html/forum/phpbb/module/module_manager.php on line 448`

**Comment by SchlesserClaude** [comment]
http://support.oneall.com/forums/discussion/comment/11345#Comment_11345
