### ISSUE TITLE
Help me: Authentication Issue, FB and Gmail user can't login

### ISSUE THREAD

**Issue by uo2022** [oneall/social-login-phpbb#69]
Help me: Authentication Issue, FB and Gmail user can't login.
My forum link is forum.yocantech.com
PS, I can use Reddit and twitter account sucess login.
Please can you help me handle this issue, thanks in advance.

But when I use FB or Gmail login, it's say need activation as below: (no any errors)

_The account has been created. However, the forum settings require account activation.
An activation key has been sent to your email address._

I have **selected Oneall_sociallogin**, but still can't login via fa or gmail.
Social Login Authentication Method
To embed Social Login into your standard login form, please login into your ACP and open the page GENERAL \ AUTHENTICATION. Then select OneAll as authentication method and save your settings.

**Comment by SchlesserClaude** [comment]
Hello,

> The account has been created. However, the forum settings require account activation.
> An activation key has been sent to your email address.

This is a settings of your phpBB. You can change it here:
**ACP ->General->Board configuration->User registration**
