### ISSUE TITLE
Language Strings are displaying incorrectly

### ISSUE THREAD

**Issue by JBodkin** [oneall/social-login-phpbb#8]
I've update to the master version from here and I'm experiencing the same problem as the current stable release version. All the strings aren't being translated properly, instead showing the placeholder.

```
OA_SOCIAL_LOGIN_TITLE_HELP

OA_SOCIAL_LOGIN_FOLLOW_US_TWITTER
OA_SOCIAL_LOGIN_READ_DOCS
OA_SOCIAL_LOGIN_DISCOVER_PLUGINS
OA_SOCIAL_LOGIN_GET_HELP
```

I've installed it at the following path: ext/oneall/sociallogin

**Comment by SchlesserClaude** [comment]
The extension includes two languages files, located here:
https://github.com/oneall/social-login-phpbb/tree/master/%5B%20%3E%3D%203.1.%20%5D%20EXTENSION/oneall/sociallogin/language

Are you using a different language? Please try renaming "en" to the code of the language that you are using.

**Comment by JBodkin** [comment]
I'm using the language British English inside the administration panel in phpbb

**Comment by fade2gray** [comment]
I got around this by making the following change to oneall/sociallogin/acp/sociallogin_acp_module.php

**Find...**
```php
	public function admin_main ()
	{
		global $db, $user, $auth, $template, $config, $phpbb_root_path, $phpbb_admin_path, $phpEx, $table_prefix;
```
**On a new line after - add...**
```php
		// Add the language file.
		$user->add_lang_ext ('oneall/sociallogin', 'backend');
```
What it doesn't fix for me is...
![](https://lh6.googleusercontent.com/-VhI_MpYqr_U/VL0AkcBf_7I/AAAAAAAABnE/VrKm0xXqjsU/s800/backend_lang.jpg)

**Comment by JBodkin** [comment]
I've managed to get the language using a slightly different approach.

Edit `oneall/sociallogin/event/listener.php`

##### Find...

```
        /**
         * Add Social Login language file.
         */
        public function add_language ($event)
        {
                $lang_set_ext = $event['lang_set_ext'];
                $lang_set_ext[] = array(
                        'ext_name' => 'oneall/sociallogin',
                        'lang_set' => 'frontend',
                );
                $event['lang_set_ext'] = $lang_set_ext;
        }
```

##### Replace with...

```
        /**
         * Add Social Login language file.
         */
        public function add_language ($event)
        {
                $lang_set_ext = $event['lang_set_ext'];
                $lang_set_ext[] = array(
                        'ext_name' => 'oneall/sociallogin',
                        'lang_set' => 'frontend',
                );
                $lang_set_ext[] = array(
                        'ext_name' => 'oneall/sociallogin',
                        'lang_set' => 'backend',
                );
                $event['lang_set_ext'] = $lang_set_ext;
        }
```

**Comment by SchlesserClaude** [comment]
Thank you very much for the solutions! I have now added them to the repository.
