### ISSUE TITLE
Unable to "enable" the plugin due to SQL error

### ISSUE THREAD

**Issue by JohnnySSH** [oneall/social-login-phpbb#9]
Hi,

I just tried both the official version and the version from github however, I'm getting the same error in each case.

I run phpBB3.1.2 with Postgresql backend; after hitting "enable" under Customize/Actions I get this:

[code]
General Error
SQL ERROR [ postgres ]

ERROR: invalid input syntax for integer: "" []

SQL

CREATE TABLE phpbb_oasl_identity ( oasl_identity_id INT4 DEFAULT nextval('phpbb_oasl_identity_seq'), oasl_user_id INT4 NULL DEFAULT '', identity_token varchar(255) NOT NULL DEFAULT '', identity_provider varchar(255) NOT NULL DEFAULT '', num_logins INT4 NULL DEFAULT '', date_added INT4 NULL DEFAULT '', date_updated INT4 NULL DEFAULT '', PRIMARY KEY (oasl_identity_id) );

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 855
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/postgres.php
LINE: 191
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\postgres->sql_query()

FILE: [ROOT]/phpbb/db/tools.php
LINE: 1428
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/phpbb/db/tools.php
LINE: 678
CALL: phpbb\db\tools->_sql_run_sql()

FILE: [ROOT]/phpbb/db/tools.php
LINE: 742
CALL: phpbb\db\tools->sql_create_table()

FILE: (not given by php)
LINE: (not given by php)
CALL: phpbb\db\tools->perform_schema_changes()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 517
CALL: call_user_func_array()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 463
CALL: phpbb\db\migrator->run_step()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 284
CALL: phpbb\db\migrator->process_data_step()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 181
CALL: phpbb\db\migrator->try_apply()

FILE: [ROOT]/phpbb/extension/base.php
LINE: 80
CALL: phpbb\db\migrator->update()

FILE: [ROOT]/phpbb/extension/manager.php
LINE: 187
CALL: phpbb\extension\base->enable_step()

FILE: [ROOT]/includes/acp/acp_extensions.php
LINE: 184
CALL: phpbb\extension\manager->enable_step()

FILE: [ROOT]/includes/functions_module.php
LINE: 674
CALL: acp_extensions->main()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()
[/code]

php version is 5.6 running in conjunction with nginx.

**Comment by SchlesserClaude** [comment]
Hello,

I have now added a commit that should fix the error:
https://github.com/oneall/social-login-phpbb/commi/0a0b95decf3fb7ebeeae85e2456544e05b6261d0

Please tell me if that does the trick.
